#============================================================================================================
# Prometheus
#============================================================================================================
run_role_prometheus: True
prometheus:
  alertmanagers:
    - localhost:9093
  scrape_targets:
    - name: prometheus
      target: localhost:9090
      labels:
        server: ansible-autobott-example
  rules_files:
    - deadManSwitch.yaml

#============================================================================================================
# Node Exporter
#============================================================================================================
run_role_node_exporter: True

#============================================================================================================
# Alertmanager
#============================================================================================================
run_role_alertmanager: True

#============================================================================================================
# Grafana
#============================================================================================================
run_role_grafana: True

#============================================================================================================
# Monit
#============================================================================================================
run_role_monit: True
monit:
  checks:
    caddy:
      enabled: true
